version: '3.2'

services:
  which-is-true:
    build: .
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -xe
        yarn install || yarn upgrade
        yarn run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app/which-is-true
